// Mock data for TechIndica prototype
// Simulates what would come from Supabase + Shopee Affiliates API + OpenAI

const CATEGORIES = [
  { slug: 'smartwatches', nome: 'Smartwatches', icone: 'watch', ordem: 1 },
  { slug: 'fones',        nome: 'Fones de Ouvido', icone: 'headphones', ordem: 2 },
  { slug: 'notebooks',    nome: 'Notebooks', icone: 'laptop', ordem: 3 },
  { slug: 'monitores',    nome: 'Monitores', icone: 'monitor', ordem: 4 },
  { slug: 'tablets',      nome: 'Tablets', icone: 'tablet', ordem: 5 },
  { slug: 'smartphones',  nome: 'Smartphones', icone: 'smartphone', ordem: 6 },
];

// Gradient palettes used as image placeholders (color-coded by category)
const GRADIENTS = {
  smartwatches: ['#fbcfe8', '#a78bfa', '#6366f1'],
  fones:        ['#fde68a', '#fb923c', '#ef4444'],
  notebooks:    ['#bae6fd', '#60a5fa', '#1d4ed8'],
  monitores:    ['#d1fae5', '#34d399', '#059669'],
  tablets:      ['#fecaca', '#f87171', '#b91c1c'],
  smartphones:  ['#e9d5ff', '#a855f7', '#7e22ce'],
};

const BADGES = {
  best:         { label: 'Melhor geral', bg: '#1e40af', fg: '#dbeafe' },
  value:        { label: 'Melhor custo-benefício', bg: '#fef3c7', fg: '#713f12' },
  editor:       { label: "Editor's Pick", bg: '#ede9fe', fg: '#4c1d95' },
  ios:          { label: 'Para iOS', bg: '#d1fae5', fg: '#065f46' },
  android:      { label: 'Para Android', bg: '#d1fae5', fg: '#065f46' },
  popular:      { label: 'Mais vendido', bg: '#fee2e2', fg: '#7f1d1d' },
};

const PRODUTOS = [
  {
    id: 101, plataforma: 'shopee', platform_id: 'sh-101',
    nome: 'Smartwatch Xiaomi Mi Band 8 Pro AMOLED 1.74" GPS Integrado',
    descricao_curta: '18 dias de bateria e GPS integrado por menos de R$ 300.',
    preco_atual: 289.90, preco_original: 449.90, desconto_pct: 36,
    link_shopee: '#', link_mercadolivre: '#',
    categoria: 'smartwatches',
    badge: 'value', nota: 9.2, publicado: true, destaque: true,
    sales: 4823,
    specs: {
      'Tela': 'AMOLED 1.74" 336×480 px',
      'Bateria': '350 mAh — até 18 dias',
      'GPS': 'GPS + GLONASS + Galileo',
      'Resistência': '5 ATM',
      'Conectividade': 'Bluetooth 5.3',
      'Compatibilidade': 'Android 8+ / iOS 12+',
      'Sensores': 'SpO2, cardíaco, temperatura',
    },
    pros: [
      '18 dias de bateria em uso real',
      'GPS multibanda integrado',
      'Tela AMOLED brilhante e nítida',
      'Resistência 5 ATM (natação)',
    ],
    contras: [
      'Sem chamadas via alto-falante',
      'Sem NFC para pagamentos',
      'App requer conta Mi',
    ],
    copy_gerada: 'Por R$ 289 na Shopee, o Mi Band 8 Pro entrega tudo o que se espera de um smartwatch intermediário — e mais. A tela AMOLED de 1.74" é a melhor da faixa de preço, e o GPS multibanda integrado elimina a necessidade do celular durante corridas e trilhas.\n\nA bateria de 350 mAh dura genuinamente 14–18 dias em uso normal, e mesmo com GPS ativado por 1h diária você ainda passa de uma semana. A resistência 5 ATM cobre natação em piscina e exposição à chuva sem preocupações.\n\nO que pesa contra: não tem NFC para pagamento por aproximação, e o app Mi Fitness ainda exige uma conta Xiaomi para funcionar. Para quem busca apenas monitoramento sério de atividade física, é o melhor custo-benefício do mercado brasileiro hoje.',
  },
  {
    id: 102, plataforma: 'shopee', platform_id: 'sh-102',
    nome: 'Smartwatch Amazfit GTR Mini 1.28" Tela AMOLED Alexa',
    descricao_curta: 'Bateria de 14 dias, Alexa integrada e visual clássico.',
    preco_atual: 449.00, preco_original: 599.00, desconto_pct: 25,
    link_shopee: '#', link_mercadolivre: '#',
    categoria: 'smartwatches',
    badge: 'editor', nota: 8.8, publicado: true, destaque: true,
    sales: 2104,
    specs: {
      'Tela': 'AMOLED 1.28" 416×416 px',
      'Bateria': '280 mAh — até 14 dias',
      'GPS': 'GPS + GLONASS + Galileo + BeiDou',
      'Resistência': '5 ATM',
      'Assistente': 'Alexa integrada',
      'Modos esportivos': '120+',
      'Compatibilidade': 'Android 7+ / iOS 12+',
    },
    pros: ['Visual clássico e leve (24g)', 'Alexa funciona offline', '120 modos esportivos', 'GPS de 4 bandas'],
    contras: ['Sem pagamento por NFC', 'Carregador proprietário', 'Tela um pouco menor'],
    copy_gerada: 'O GTR Mini é a aposta da Amazfit para quem prefere um relógio que pareça relógio. Com 24g e moldura de alumínio, ele desaparece no pulso — mas a tela AMOLED de 1.28" entrega tudo que você espera ver.\n\nA Alexa integrada funciona até mesmo sem internet pareada, e os 120 modos esportivos cobrem desde tênis de mesa até skateboard. Bateria genuína de 14 dias em uso misto.',
  },
  {
    id: 103, plataforma: 'shopee', platform_id: 'sh-103',
    nome: 'Apple Watch Series 9 GPS 45mm Alumínio Meia-noite',
    descricao_curta: 'O melhor smartwatch para iPhone, com chip S9 e tela 2x mais brilhante.',
    preco_atual: 3299.00, preco_original: 3999.00, desconto_pct: 18,
    link_shopee: '#', link_mercadolivre: '#',
    categoria: 'smartwatches',
    badge: 'ios', nota: 9.5, publicado: true, destaque: false,
    sales: 892,
    specs: {
      'Tela': 'Retina LTPO OLED 484×396',
      'Chip': 'Apple S9 SiP',
      'Bateria': 'Até 18h (36h economia)',
      'Resistência': 'WR50 + IP6X',
      'Conectividade': 'GPS, Wi-Fi 4, BT 5.3, UWB 2ª gen',
      'Compatibilidade': 'iOS 17+',
    },
    pros: ['Integração total com iPhone', 'Tela 2000 nits muito brilhante', 'Double Tap funciona bem', 'ECG e oxigenação'],
    contras: ['Bateria só de 1 dia', 'Não funciona com Android', 'Preço alto'],
    copy_gerada: 'Para quem tem iPhone, não há substituto. O Series 9 traz o chip S9, gestos Double Tap e tela 2000 nits que é legível sob sol forte.\n\nA bateria continua sendo o calcanhar de Aquiles — você carrega todo dia. Mas o ecossistema Apple compensa: pagamento Apple Pay, destrava o Mac, encontra AirPods perdidos.',
  },
  {
    id: 201, plataforma: 'shopee', platform_id: 'sh-201',
    nome: 'Fone Bluetooth JBL Tune 510BT Sem Fio Pure Bass 40h',
    descricao_curta: '40 horas de bateria, JBL Pure Bass e dobrável por R$ 199.',
    preco_atual: 199.00, preco_original: 349.00, desconto_pct: 43,
    link_shopee: '#', link_mercadolivre: '#',
    categoria: 'fones',
    badge: 'popular', nota: 8.5, publicado: true, destaque: true,
    sales: 12480,
    specs: {
      'Tipo': 'Over-ear sem fio',
      'Bateria': '40h reprodução',
      'Bluetooth': '5.0 Multipoint',
      'Drivers': '32mm — JBL Pure Bass',
      'Peso': '160g',
      'Recarga': 'USB-C — 5min = 2h',
    },
    pros: ['40h reais de bateria', 'JBL Pure Bass marcante', 'Dobrável e portátil', 'Multipoint funciona'],
    contras: ['Sem cancelamento de ruído ativo', 'Almofadas de espuma sintética', 'Cabo aux não acompanha'],
    copy_gerada: 'Os 510BT são o "queridinho" da JBL na faixa abaixo de R$ 200. Com 40h reais de bateria, dobráveis e com som assinatura Pure Bass, eles cobrem 90% dos casos de uso.\n\nNão espere ANC ou drivers premium — mas para trabalhar em casa, estudar ou ouvir música no transporte, o conjunto é difícil de bater pelo preço.',
  },
  {
    id: 202, plataforma: 'shopee', platform_id: 'sh-202',
    nome: 'Fone In-Ear Sony WF-C700N ANC Bluetooth 5.2',
    descricao_curta: 'ANC eficaz, leve e com som Sony por menos de R$ 600.',
    preco_atual: 579.00, preco_original: 799.00, desconto_pct: 28,
    link_shopee: '#', link_mercadolivre: '#',
    categoria: 'fones',
    badge: 'value', nota: 9.0, publicado: true, destaque: true,
    sales: 1820,
    specs: {
      'Tipo': 'TWS In-ear ANC',
      'Bateria': '7,5h + 15h com estojo',
      'Bluetooth': '5.2 Multipoint',
      'Drivers': '5mm dinâmico',
      'Codecs': 'SBC, AAC',
      'Resistência': 'IPX4',
    },
    pros: ['ANC realmente funciona', 'App Sony muito completo', 'Multipoint estável', 'Peso ridículo (4.6g cada)'],
    contras: ['Sem LDAC nem aptX', 'Case sem carregamento sem fio', 'Modelo branco amarela com o tempo'],
    copy_gerada: 'A Sony finalmente fez o "irmão menor" dos WF-1000XM5 — e ele entrega. O ANC do C700N silencia ruído de ônibus e ar-condicionado de forma convincente.\n\nO app permite EQ por banda, modo ambiente personalizado e atalhos por gesto. Falta LDAC e aptX, mas para Spotify e YouTube Music o AAC dá conta.',
  },
  {
    id: 301, plataforma: 'shopee', platform_id: 'sh-301',
    nome: 'Notebook Lenovo IdeaPad 3i i5-1235U 16GB 512GB SSD 15.6"',
    descricao_curta: '16GB RAM e SSD 512GB num i5 de 12ª por menos de R$ 3.500.',
    preco_atual: 3299.00, preco_original: 4499.00, desconto_pct: 27,
    link_shopee: '#', link_mercadolivre: '#',
    categoria: 'notebooks',
    badge: 'value', nota: 8.7, publicado: true, destaque: true,
    sales: 643,
    specs: {
      'Processador': 'Intel Core i5-1235U (10 núcleos)',
      'RAM': '16 GB DDR4 3200MHz',
      'Armazenamento': 'SSD NVMe 512 GB',
      'Tela': '15.6" Full HD IPS 60Hz',
      'Bateria': '38Wh — até 7h',
      'Peso': '1.62 kg',
      'Portas': '2x USB-A, 1x USB-C, HDMI, RJ-45',
    },
    pros: ['16GB de RAM é exceção na faixa', 'i5 12ª gen tem ótimo desempenho', 'SSD NVMe rápido', 'Teclado numérico'],
    contras: ['Tela 250 nits — fraca em ambiente claro', 'Sem retroiluminação no teclado', 'Plástico ranha fácil'],
    copy_gerada: 'O IdeaPad 3i com i5-1235U e 16GB é o ponto doce do mercado de notebooks para trabalho híbrido. O processador roda Excel pesado, Chrome com 30 abas e até edição de fotos em RAW sem suar.\n\nA tela 250 nits é o ponto fraco — se você trabalha próximo a janelas, considere subir para a versão IPS 300 nits. Para uso interno, é fluida e nítida.',
  },
  {
    id: 401, plataforma: 'shopee', platform_id: 'sh-401',
    nome: 'Monitor Gamer LG UltraGear 27" 165Hz 1ms IPS QHD',
    descricao_curta: 'QHD 165Hz em painel IPS por menos de R$ 1.700.',
    preco_atual: 1699.00, preco_original: 2399.00, desconto_pct: 29,
    link_shopee: '#', link_mercadolivre: null,
    categoria: 'monitores',
    badge: 'editor', nota: 9.1, publicado: true, destaque: true,
    sales: 410,
    specs: {
      'Tela': '27" IPS QHD 2560×1440',
      'Taxa': '165 Hz',
      'Resposta': '1 ms (GtG)',
      'Sincronização': 'FreeSync Premium + G-SYNC Compatible',
      'HDR': 'HDR10',
      'Portas': '2x HDMI 2.0, 1x DisplayPort',
      'Cobertura': 'sRGB 99%',
    },
    pros: ['IPS QHD a 165Hz é o ponto doce', 'Cobertura sRGB 99% serve para design', 'Suporte ergonômico ajustável', 'FreeSync + G-Sync funcionam'],
    contras: ['HDR é mais marketing que prática', 'Sem USB hub', 'Stand grande ocupa mesa'],
    copy_gerada: 'O UltraGear 27GP750 é o monitor que mais entrega por R$ 1.700 hoje no Brasil. QHD a 165Hz num painel IPS é a combinação ideal para quem joga e também trabalha com cores.\n\nA cobertura sRGB de 99% é suficiente para edição de fotos não-profissional, e o tempo de resposta de 1ms (com overdrive) elimina motion blur em jogos rápidos.',
  },
  {
    id: 501, plataforma: 'shopee', platform_id: 'sh-501',
    nome: 'Tablet Samsung Galaxy Tab S6 Lite 2024 10.4" 128GB Wi-Fi',
    descricao_curta: 'S Pen incluída, OneUI 6 e atualizações até 2028.',
    preco_atual: 1799.00, preco_original: 2299.00, desconto_pct: 22,
    link_shopee: '#', link_mercadolivre: '#',
    categoria: 'tablets',
    badge: 'best', nota: 8.6, publicado: true, destaque: false,
    sales: 1102,
    specs: {
      'Tela': '10.4" TFT LCD 2000×1200',
      'Processador': 'Exynos 1280 octa-core',
      'RAM': '4 GB',
      'Armazenamento': '128 GB + microSD',
      'Bateria': '7040 mAh',
      'Caneta': 'S Pen inclusa',
      'Som': '4 alto-falantes Dolby Atmos',
    },
    pros: ['S Pen acompanha de fábrica', '4 alto-falantes com Atmos', 'Atualizações garantidas até 2028', 'Bom para anotações em PDF'],
    contras: ['Não é AMOLED', 'Só 4GB de RAM', 'Câmera traseira fraca'],
    copy_gerada: 'O Tab S6 Lite 2024 é o tablet Android com melhor relação custo-benefício para estudantes. A S Pen vem na caixa, e o app Samsung Notes integra bem com OneNote e Goodnotes.',
  },
  {
    id: 102.5, plataforma: 'shopee', platform_id: 'sh-301-NULL', // intentionally bad / pending product
    nome: 'Caixa de Som Bluetooth JBL Go 3 Eco — produto pendente',
    descricao_curta: '', // empty: not yet generated
    preco_atual: 189.00, preco_original: 249.00, desconto_pct: 24,
    link_shopee: '#', link_mercadolivre: null,
    categoria: null, // pending categorization
    badge: null, nota: null, publicado: false, destaque: false,
    sales: 0,
    specs: null, pros: null, contras: null, copy_gerada: null,
  },
];

const EXEC_LOG = [
  { id: 9821, plataforma: 'shopee', status: 'success', encontrados: 18, publicados: 16, erro: null, created_at: '2026-05-22T07:14:00Z' },
  { id: 9820, plataforma: 'shopee', status: 'success', encontrados: 22, publicados: 22, erro: null, created_at: '2026-05-21T07:14:00Z' },
  { id: 9819, plataforma: 'shopee', status: 'partial', encontrados: 14, publicados: 11, erro: '3 produtos falharam na geração de copy (timeout OpenAI)', created_at: '2026-05-20T07:14:00Z' },
  { id: 9818, plataforma: 'shopee', status: 'success', encontrados: 19, publicados: 19, erro: null, created_at: '2026-05-19T07:14:00Z' },
  { id: 9817, plataforma: 'shopee', status: 'error', encontrados: 0, publicados: 0, erro: 'Assinatura HMAC inválida (timestamp drift)', created_at: '2026-05-18T07:14:00Z' },
  { id: 9816, plataforma: 'shopee', status: 'success', encontrados: 24, publicados: 24, erro: null, created_at: '2026-05-17T07:14:00Z' },
  { id: 9815, plataforma: 'shopee', status: 'success', encontrados: 16, publicados: 15, erro: null, created_at: '2026-05-16T07:14:00Z' },
];

// 30 day chart data: produtos adicionados por dia
const CHART_DATA = [4,6,3,8,12,9,5,7,11,14,8,10,9,6,12,15,11,8,10,13,9,7,11,16,18,14,12,10,16,18];

Object.assign(window, {
  CATEGORIES, PRODUTOS, BADGES, GRADIENTS, EXEC_LOG, CHART_DATA,
});
